name: build

on: [ push ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t akai-discord-bot:latest .
      - name: Run the Docker container
        run: docker run -d --name=akai-discord-bot akai-discord-bot